version: "3"

volumes:
  database_data:

services:
  discord-bot:
    build: .
    environment:
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DISCORD_APP_ID: ${DISCORD_APP_ID}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DEBUG: "true"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    volumes:
      - database_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
